In [9]:
# Impor library
# Impor library yang dibutuhkan
from sklearn.neural_network import MLPClassifier as neuralNetwork
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd
import numpy as np
import joblib as jbl

In [2]:
# Impor dataset
dataset_latih = pd.read_csv('./dataset_latih_final.csv')

# Acak urutan dataset
dataset_latih = dataset_latih.sample(frac = 1, random_state = 2025, ignore_index = True)

In [3]:
# Tetapkan fitur dan label latih
fitur_latih = dataset_latih[['jenisKelamin', 'umur', 'beratBadan', 'tinggiBadan']]
target_latih = dataset_latih['label']

In [4]:
# Buat model jaringan pertama sesuai dengan hasil cross-validation
modelAnn_kedua_1 = neuralNetwork(hidden_layer_sizes=(9,4),
                           activation='relu',
                           solver='adam',
                           batch_size=4,
                           learning_rate_init=0.01,
                           max_iter=600)

modelAnn_kedua_2 = neuralNetwork(hidden_layer_sizes=(9,4),
                           activation='relu',
                           solver='adam',
                           batch_size=4,
                           learning_rate_init=0.01,
                           max_iter=1000)

modelAnn_kedua_3 = neuralNetwork(hidden_layer_sizes=(9,4),
                           activation='relu',
                           solver='adam',
                           batch_size=4,
                           learning_rate_init=0.01,
                           max_iter=2200)

modelAnn_kedua_4 = neuralNetwork(hidden_layer_sizes=(9,4),
                           activation='relu',
                           solver='adam',
                           batch_size=8,
                           learning_rate_init=0.001,
                           max_iter=600)

modelAnn_kedua_5 = neuralNetwork(hidden_layer_sizes=(9,4),
                           activation='relu',
                           solver='adam',
                           batch_size=8,
                           learning_rate_init=0.001,
                           max_iter=1000)

modelAnn_kedua_6 = neuralNetwork(hidden_layer_sizes=(9,4),
                           activation='relu',
                           solver='adam',
                           batch_size=8,
                           learning_rate_init=0.001,
                           max_iter=2200)

In [5]:
# Latih model jaringan
modelAnn_kedua_1.fit(fitur_latih, target_latih)
modelAnn_kedua_2.fit(fitur_latih, target_latih)
modelAnn_kedua_3.fit(fitur_latih, target_latih)
modelAnn_kedua_4.fit(fitur_latih, target_latih)
modelAnn_kedua_5.fit(fitur_latih, target_latih)
modelAnn_kedua_6.fit(fitur_latih, target_latih)

MLPClassifier(batch_size=8, hidden_layer_sizes=(9, 4), max_iter=2200)

In [6]:
# Impor dataset uji
dataset_uji = pd.read_csv('./dataset_uji_final.csv')

# Tetapkan fitur dan label uji
fitur_uji = dataset_uji[['jenisKelamin', 'umur', 'beratBadan', 'tinggiBadan']]
target_uji = dataset_uji['label']

In [7]:
# Uji jaringan kedua
hasilAnn_kedua_1 = modelAnn_kedua_1.predict(fitur_uji)
hasilAnn_kedua_2 = modelAnn_kedua_2.predict(fitur_uji)
hasilAnn_kedua_3 = modelAnn_kedua_3.predict(fitur_uji)
hasilAnn_kedua_4 = modelAnn_kedua_4.predict(fitur_uji)
hasilAnn_kedua_5 = modelAnn_kedua_5.predict(fitur_uji)
hasilAnn_kedua_6 = modelAnn_kedua_6.predict(fitur_uji)

In [8]:
# Cek performa seluruh tipe model pertama
print('Tipe 1 - Model kedua')
print(classification_report(target_uji, hasilAnn_kedua_1, zero_division=0))
print(confusion_matrix(target_uji, hasilAnn_kedua_1))

print('Tipe 2 - Model kedua')
print(classification_report(target_uji, hasilAnn_kedua_2, zero_division=0))
print(confusion_matrix(target_uji, hasilAnn_kedua_2))

print('Tipe 3 - Model kedua')
print(classification_report(target_uji, hasilAnn_kedua_3, zero_division=0))
print(confusion_matrix(target_uji, hasilAnn_kedua_3))

print('Tipe 4 - Model kedua')
print(classification_report(target_uji, hasilAnn_kedua_4, zero_division=0))
print(confusion_matrix(target_uji, hasilAnn_kedua_4))

print('Tipe 5 - Model kedua')
print(classification_report(target_uji, hasilAnn_kedua_5, zero_division=0))
print(confusion_matrix(target_uji, hasilAnn_kedua_5))

print('Tipe 6 - Model kedua')
print(classification_report(target_uji, hasilAnn_kedua_6, zero_division=0))
print(confusion_matrix(target_uji, hasilAnn_kedua_6))

Tipe 1 - Model kedua
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         6
           1       1.00      0.16      0.28       110
           2       0.42      0.62      0.50         8
           3       0.39      0.98      0.56        61

    accuracy                           0.45       185
   macro avg       0.45      0.44      0.33       185
weighted avg       0.74      0.45      0.37       185

[[ 0  0  5  1]
 [ 0 18  1 91]
 [ 0  0  5  3]
 [ 0  0  1 60]]
Tipe 2 - Model kedua
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         6
           1       1.00      0.15      0.27       110
           2       0.56      0.62      0.59         8
           3       0.38      1.00      0.55        61

    accuracy                           0.45       185
   macro avg       0.48      0.44      0.35       185
weighted avg       0.75      0.45      0.37       185

[[ 0  0  4  2]
 [ 0 17  0 9

In [11]:
# Simpan seluruh tipe pada model jaringan kedua
jbl.dump(modelAnn_kedua_1, 'model_kedua_1.pkl')
jbl.dump(modelAnn_kedua_2, 'model_kedua_2.pkl')
jbl.dump(modelAnn_kedua_3, 'model_kedua_3.pkl')
jbl.dump(modelAnn_kedua_4, 'model_kedua_4.pkl')
jbl.dump(modelAnn_kedua_5, 'model_kedua_5.pkl')
jbl.dump(modelAnn_kedua_6, 'model_kedua_6.pkl')

['model_kedua_6.pkl']