In [284]:
# impor library yang dibutuhkan
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np

In [285]:
# impor dataset
pemkomedan = pd.read_csv('../raw-datasets/Dataset-PemkoMedan.csv', delimiter=';', decimal=',')

In [286]:
# cek total data
pemkomedan.count()

L/P           314
Umur (bln)    314
BB (Kg)       314
Tb (Cm)       313
dtype: int64

In [287]:
# cek tipe data
pemkomedan.dtypes

L/P           object
Umur (bln)    object
BB (Kg)       object
Tb (Cm)       object
dtype: object

In [288]:
# ubah nama fitur
pemkomedan.rename(columns={"L/P":"jenisKelamin", "Umur (bln)":"umur", "BB (Kg)":"beratBadan", "Tb (Cm)":"tinggiBadan"}, inplace=True)

In [291]:
# cek data label jenisKelamin
pemkomedan.jenisKelamin.unique()

array(['P', 'L'], dtype=object)

In [290]:
# selaraskan label jenisKelamin
pemkomedan.jenisKelamin = pemkomedan.jenisKelamin.replace(['pr', 'p'], 'P')
pemkomedan.jenisKelamin = pemkomedan.jenisKelamin.replace(['lk', 'L '], 'L')

In [295]:
# cek data label umur
pemkomedan.umur.unique()

array([44, 42, 37, 36, 29, 23, 56, 35, 45, 18, 24, 43, 48, 52, 58, 51, 38,
       49, 15, 22, 55, 16, 26, 32, 14, 41, 39, 33, 34, 40, 47, 50, 17, 28,
       31, 19, 20, 46, 30,  6, 57, 21, 59, 60, 25, 13, 27, 53,  1,  7, 54])

In [293]:
# memperbaiki label umur
clean_umur_1 = pemkomedan.loc[pemkomedan.umur.str.contains('Bln|Bin|BLn'), 'umur'].str[0:-3].str.replace(' ', '')
clean_umur_2 = pemkomedan.loc[pemkomedan.umur.str.contains('Bulan'), 'umur'].str[0:-5].str.replace(' ', '')
# mengganti nilai umur
pemkomedan.loc[pemkomedan.umur.str.contains('Bln|Bin|BLn'), 'umur'] = clean_umur_1
pemkomedan.loc[pemkomedan.umur.str.contains('Bulan'), 'umur'] = clean_umur_2

In [294]:
# ubah LEWATUMUR menjadi nan
pemkomedan.umur = pemkomedan.umur.replace('LEWATUMUR', np.nan)
# cari nilai mean
umur_notNa = pemkomedan.loc[pemkomedan.umur.notna(),'umur']
mean_umur = umur_notNa.astype('int64').mean().round()
# isi nilai nan menggunakan mean
pemkomedan.umur = pemkomedan.umur.fillna(mean_umur)
pemkomedan.umur = pemkomedan.umur.astype('int64')

In [300]:
# cek data label tinggiBadan
pemkomedan.tinggiBadan.unique()

array([ 90.5,  94. ,  88. ,  84.5,  86. ,  81.5,  76.5,  85. ,  86.5,
        84. ,  92.5,  74.5,  77.5,  88.5,  91.2,  91. ,  98. ,  90. ,
        93. ,  68. ,  74. ,  93.5,  72. ,  69. ,  79. ,  89. ,  92. ,
        78. ,  70. ,  64. ,  87. ,  91.5,  99. ,  96. ,  83. ,  81. ,
        76. ,  73.4,  80.5,  87.1,  84.1,  85.7,  92.7,  83.5,  73. ,
        72.5,  81.2,  60. ,  89.5,  95. ,  96.5, 100.2,  82. ,  89.2,
        80. ,  75.5,  75. ,  77. , 867. ,  94.5, 884. ,  81.6,  94.6,
        67. ,  87.5,  57. ,  93.3,  88.1,  78.2,  71. ])

In [297]:
# isi nilai nan untuk mencegah eror
pemkomedan.tinggiBadan = pemkomedan.tinggiBadan.fillna('LEWATUMUR')

In [298]:
# memperbaiki label tinggiBadan
clean_tinggiBadan = pemkomedan.loc[pemkomedan.tinggiBadan.str.contains('cm'),'tinggiBadan'].str[0:-2].str.replace(' ', '')
# mengganti nilai tinggibadan 
pemkomedan.loc[pemkomedan.tinggiBadan.str.contains('cm'), 'tinggiBadan'] = clean_tinggiBadan
# mengganti koma menjadi titik
pemkomedan.tinggiBadan = pemkomedan.tinggiBadan.str.replace(',', '.')

In [299]:
# mengubah LEWATUMUR dengan nan
pemkomedan.tinggiBadan = pemkomedan.tinggiBadan.replace('LEWATUMUR', np.nan)
# mencari nilai mean
tinggi_notNa = pemkomedan.loc[pemkomedan.tinggiBadan.notna()]
mean_tinggi = tinggi_notNa.tinggiBadan.astype('float64').mean().round(1)
# mengisi nilai na dengan nilai mean
pemkomedan.tinggiBadan = pemkomedan.tinggiBadan.fillna(mean_tinggi)
pemkomedan.tinggiBadan = pemkomedan.tinggiBadan.astype('float64')

In [305]:
# cek data label tinggiBadan
pemkomedan.beratBadan.unique()

array([13.  , 12.2 , 10.  ,  9.7 , 11.  ,  7.2 ,  9.4 , 13.2 , 11.5 ,
        7.5 ,  9.  , 11.9 , 12.  , 11.4 , 10.2 ,  5.6 ,  7.3 ,  6.9 ,
        6.5 ,  8.  ,  9.9 ,  7.  , 11.2 , 11.7 ,  9.3 ,  8.4 ,  5.7 ,
        9.2 , 10.3 , 11.3 , 10.9 , 12.3 , 12.8 , 10.4 ,  8.8 , 11.8 ,
        9.1 , 10.1 , 10.8 ,  7.8 ,  8.7 , 14.  , 10.5 , 12.5 , 13.5 ,
        8.5 , 14.2 , 14.3 ,  5.4 , 10.7 , 12.1 , 14.4 , 10.6 , 12.9 ,
        8.9 , 14.8 , 14.6 ,  9.8 , 11.6 ,  8.3 ,  8.6 ,  7.7 ,  6.6 ,
        9.5 ,  9.6 ,  6.8 , 11.35,  9.45, 12.6 ,  8.2 ,  6.7 ,  5.  ,
        7.1 , 13.7 , 13.6 , 13.3 , 14.7 ,  6.3 , 13.8 ,  7.9 ,  7.6 ])

In [302]:
# isi nilai nan untuk mencegah eror
pemkomedan.beratBadan = pemkomedan.beratBadan.fillna('LEWATUMUR')

In [303]:
# memperbaiki label beratBadan
clean_beratBadan = pemkomedan.loc[pemkomedan.beratBadan.str.contains('kg|Kg|KG'),'beratBadan'].str[0:-2].str.replace(' ', '')
# mengganti nilai beratBadan 
pemkomedan.loc[pemkomedan.beratBadan.str.contains('kg|Kg|KG'), 'beratBadan'] = clean_beratBadan
# mengganti koma menjadi titik
pemkomedan.beratBadan = pemkomedan.beratBadan.str.replace(',', '.')

In [304]:
# mengubah LEWATUMUR dengan nan
pemkomedan.beratBadan = pemkomedan.beratBadan.replace('LEWATUMUR', np.nan)
# mencari nilai mean
berat_notNa = pemkomedan.loc[pemkomedan.beratBadan.notna()]
mean_berat = berat_notNa.beratBadan.astype('float64').mean().round(1)
# mengisi nilai na dengan nilai mean
pemkomedan.beratBadan = pemkomedan.beratBadan.fillna(mean_berat)
pemkomedan.beratBadan = pemkomedan.beratBadan.astype('float64')

In [306]:
# cek tipe data
pemkomedan.dtypes

jenisKelamin     object
umur              int64
beratBadan      float64
tinggiBadan     float64
dtype: object

In [307]:
# hapus noise pada seluruh fitur
noise_umur = pemkomedan.loc[(pemkomedan.umur < 0) | (pemkomedan.umur > 60)]
pemkomedan.drop(index = noise_umur.index, inplace=True)
noise_berat = pemkomedan.loc[(pemkomedan.beratBadan < 1.9) | (pemkomedan.beratBadan > 31.2)]
pemkomedan.drop(index = noise_berat.index, inplace=True)
noise_tinggi = pemkomedan.loc[(pemkomedan.tinggiBadan < 43.6 ) | (pemkomedan.tinggiBadan > 123.9)]
pemkomedan.drop(index = noise_tinggi.index, inplace=True)

In [312]:
# hapus data duplikat
pemkomedan.drop_duplicates(inplace=True)

In [313]:
# acak susunan dataset
pemkomedan = pemkomedan.sample(frac=1, ignore_index=True, random_state=18062025)

In [314]:
# ekspor dataset
pemkomedan.to_csv('pemkomedan-clean.csv', index=False)